name: Trigger auto deployment for chatbot-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/chatbot-ui-AutoDeployTrigger-9b89bf24-d676-41bb-a0d9-45ea4530d9cf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CHATBOTUI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CHATBOTUI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CHATBOTUI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CHATBOTUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CHATBOTUI_REGISTRY_PASSWORD }}
          containerAppName: chatbot-ui
          resourceGroup: RBW-Global-EastUS2
          imageToBuild: ghcr.io/chatbot-ui:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


